import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { Bell, CalendarDays, ClipboardList, CreditCard, Dumbbell, GraduationCap, LayoutDashboard, Menu, Pencil, Plus, Search, Settings, Trash2, Users, X } from 'lucide-react'
import './App.css'

type Entity = 'Alunos' | 'Planos' | 'Treinos' | 'Instrutores' | 'Pagamentos'
type Page = 'Visão geral' | Entity
type Item = Record<string, any>
type Store = Record<Entity, Item[]> & { connected: boolean }
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3000'
const paths: Record<Entity, string> = { Alunos:'/alunos', Planos:'/planos', Treinos:'/treinos', Instrutores:'/clientes', Pagamentos:'/pagamentos' }
const keys: Record<Entity, string> = { Alunos:'id_aluno', Planos:'id_plano', Treinos:'id_treino', Instrutores:'id_instrutor', Pagamentos:'id_pagamento' }
const singular: Record<Entity, string> = { Alunos:'aluno', Planos:'plano', Treinos:'treino', Instrutores:'instrutor', Pagamentos:'pagamento' }
const avatar = 'https://i.pravatar.cc/100?img=5'
const now = () => new Date().toISOString()
const today = () => now().slice(0, 10)
const money = (n:number) => Number(n || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const date = (v:string) => v ? new Date(v).toLocaleDateString('pt-BR') : '—'
const fallback: Store = {
  Alunos:[{id_aluno:1,nome:'Marina Oliveira',data_nascimento:1995,email:'marina.oliveira@email.com',telefone:11987654321,data_cadastro:'2026-09-01',foto:'https://i.pravatar.cc/100?img=47',id_plano:1,status:now()},{id_aluno:2,nome:'Lucas Mendes',data_nascimento:1998,email:'lucas@email.com',telefone:11976543210,data_cadastro:'2026-09-03',foto:'https://i.pravatar.cc/100?img=12',id_plano:2,status:now()}],
  Planos:[{id_plano:1,nome_plano:'Performance',descricao:'Acompanhamento completo',duracao_meses:3,valor_plano:289.9,ativo:true},{id_plano:2,nome_plano:'Essencial',descricao:'Treinos personalizados',duracao_meses:1,valor_plano:149.9,ativo:true}],
  Instrutores:[{id_instrutor:1,nome:'Rafael Costa',email:'rafael@movimente.com',telefone:11999999999,especialidade:'Musculação',ativo:true,foto:'https://i.pravatar.cc/100?img=13'}],
  Treinos:[{id_treino:1,id_aluno:1,id_instrutor:1,objetivo:'Hipertrofia',observacoes:'Treino A/B, 4x por semana.',data_entrada:now(),data_saida:now()}],
  Pagamentos:[{id_pagamento:1,id_aluno:1,id_plano:1,data_pagamento:now(),data_vencimento:'2026-09-12',valor:289.9,metodo:'PIX',status_pagamento:'Pago'},{id_pagamento:2,id_aluno:2,id_plano:2,data_vencimento:'2026-09-14',valor:149.9,metodo:'Cartao',status_pagamento:'Pendente'}],connected:false
}
const fields: Record<Entity,{key:string; label:string; type?:string; options?:string[]}[]> = {
  Alunos:[{key:'nome',label:'Nome completo'},{key:'email',label:'E-mail',type:'email'},{key:'telefone',label:'Telefone',type:'number'},{key:'data_nascimento',label:'Ano de nascimento',type:'number'},{key:'id_plano',label:'Plano',type:'plan'},{key:'data_cadastro',label:'Data de cadastro',type:'date'},{key:'foto',label:'URL da foto'}],
  Planos:[{key:'nome_plano',label:'Nome do plano'},{key:'descricao',label:'Descrição',type:'textarea'},{key:'duracao_meses',label:'Duração (meses)',type:'number'},{key:'valor_plano',label:'Valor',type:'number'},{key:'ativo',label:'Status',type:'boolean'}],
  Instrutores:[{key:'nome',label:'Nome completo'},{key:'email',label:'E-mail',type:'email'},{key:'telefone',label:'Telefone',type:'number'},{key:'especialidade',label:'Especialidade'},{key:'foto',label:'URL da foto'},{key:'ativo',label:'Status',type:'boolean'}],
  Treinos:[{key:'id_aluno',label:'Aluno',type:'student'},{key:'id_instrutor',label:'Instrutor',type:'instructor'},{key:'objetivo',label:'Objetivo'},{key:'observacoes',label:'Observações',type:'textarea'}],
  Pagamentos:[{key:'id_aluno',label:'Aluno',type:'student'},{key:'id_plano',label:'Plano',type:'plan'},{key:'valor',label:'Valor',type:'number'},{key:'data_vencimento',label:'Vencimento',type:'date'},{key:'metodo',label:'Método',options:['Dinheiro','Cartao','PIX']},{key:'status_pagamento',label:'Status',options:['Pendente','Pago','Atrasado']}]
}
const defaults: Record<Entity,Item> = { Alunos:{nome:'',email:'',telefone:0,data_nascimento:2000,id_plano:1,data_cadastro:today(),foto:avatar,status:now()},Planos:{nome_plano:'',descricao:'',duracao_meses:1,valor_plano:0,ativo:true},Instrutores:{nome:'',email:'',telefone:0,especialidade:'',foto:avatar,ativo:true},Treinos:{id_aluno:1,id_instrutor:1,objetivo:'',observacoes:'',data_entrada:now(),data_saida:now()},Pagamentos:{id_aluno:1,id_plano:1,valor:0,data_pagamento:now(),data_vencimento:today(),metodo:'PIX',status_pagamento:'Pendente'} }

export default function App() {
  const [page,setPage] = useState<Page>('Visão geral'), [store,setStore] = useState<Store>(fallback), [query,setQuery] = useState(''), [menu,setMenu] = useState(false), [editing,setEditing] = useState<{entity:Entity;value?:Item}|null>(null)
  useEffect(() => { Promise.all((Object.keys(paths) as Entity[]).map(async entity => [entity,await fetch(API+paths[entity]).then(r=>r.ok?r.json():Promise.reject())] as const)).then(items=>setStore(s=>({...s,...Object.fromEntries(items),connected:true}))).catch(()=>undefined) },[])
  const navigate=(p:Page)=>{setPage(p);setQuery('');setMenu(false)}
  const save=async(entity:Entity,value:Item)=>{ const id=value[keys[entity]]; let saved=value; try { const r=await fetch(`${API}${paths[entity]}${id?`/${id}`:''}`,{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});if(r.ok)saved=await r.json() } catch {/* modo local */} setStore(s=>{const items=s[entity], item=id?saved:{...saved,[keys[entity]]:items.length?Math.max(...items.map(x=>Number(x[keys[entity]])))+1:1};return {...s,[entity]:id?items.map(x=>x[keys[entity]]===id?item:x):[...items,item]}});setEditing(null)}
  const remove=async(entity:Entity,id:number)=>{if(!confirm(`Excluir este ${singular[entity]}?`))return;try{await fetch(`${API}${paths[entity]}/${id}`,{method:'DELETE'})}catch{}setStore(s=>({...s,[entity]:s[entity].filter(x=>x[keys[entity]]!==id)}))}
  const pending=store.Pagamentos.filter(x=>x.status_pagamento!=='Pago').length
  const nav:[Page,any][]=[['Visão geral',LayoutDashboard],['Alunos',Users],['Planos',ClipboardList],['Treinos',Dumbbell],['Instrutores',GraduationCap],['Pagamentos',CreditCard]]
  return <div className="app-shell"><aside className={`sidebar ${menu?'sidebar-open':''}`}><div className="brand"><span className="brand-mark"><Dumbbell size={20}/></span><span>movimente</span><button className="icon-button close-menu" onClick={()=>setMenu(false)}><X/></button></div><div className="workspace-label">GESTÃO DA ACADEMIA</div><nav>{nav.map(([name,Icon])=><button key={name} className={`nav-item ${page===name?'active':''}`} onClick={()=>navigate(name)}><Icon size={18}/><span>{name}</span>{name==='Alunos'&&<span className="nav-count">{store.Alunos.length}</span>}{name==='Pagamentos'&&!!pending&&<span className="nav-alert">{pending}</span>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings size={18}/><span>Configurações</span></button><div className="profile"><div className="avatar">RC</div><div><strong>Rafael Costa</strong><small>Administrador</small></div></div></div></aside><main className="main-content"><header className="topbar"><button className="icon-button menu-button" onClick={()=>setMenu(true)}><Menu size={22}/></button><div className="breadcrumb"><span>Academia</span><b>/</b><strong>{page}</strong></div><div className="topbar-actions"><span className={`api-status ${store.connected?'online':''}`}><i/>{store.connected?'API conectada':'Modo demonstração'}</span><button className="icon-button notification-button"><Bell size={19}/></button><div className="top-avatar">RC</div></div></header><div className="page-content">{page==='Visão geral'?<Dashboard store={store} go={navigate}/>:<List entity={page} store={store} query={query} setQuery={setQuery} edit={x=>setEditing({entity:page,value:x})} create={()=>setEditing({entity:page})} remove={remove}/>}</div><footer><span>Movimente · Gestão inteligente para sua academia</span><span>Última atualização: agora</span></footer></main>{editing&&<Form entity={editing.entity} value={editing.value} store={store} close={()=>setEditing(null)} save={save}/>}</div>
}
function Dashboard({store,go}:{store:Store;go:(p:Page)=>void}){const received=store.Pagamentos.filter(x=>x.status_pagamento==='Pago').reduce((n,x)=>n+Number(x.valor),0);return <><section className="page-heading"><div><p className="eyebrow">GESTÃO DA ACADEMIA</p><h1>Bom dia, Rafael <span>✦</span></h1><p className="subheading">Acompanhe a rotina e os resultados da sua academia.</p></div><button className="primary-button" onClick={()=>go('Alunos')}><Plus size={18}/>Nova matrícula</button></section><section className="metrics-grid"><Card icon={<Users/>} label="Alunos cadastrados" value={String(store.Alunos.length)}/><Card icon={<ClipboardList/>} label="Planos ativos" value={String(store.Planos.filter(x=>x.ativo).length)}/><Card icon={<CreditCard/>} label="Receita recebida" value={money(received)}/><Card icon={<CalendarDays/>} label="Pagamentos pendentes" value={String(store.Pagamentos.filter(x=>x.status_pagamento!=='Pago').length)}/></section><section className="dashboard-actions"><button onClick={()=>go('Treinos')}><Dumbbell/>Gerenciar treinos</button><button onClick={()=>go('Pagamentos')}><CreditCard/>Abrir financeiro</button><button onClick={()=>go('Instrutores')}><GraduationCap/>Ver instrutores</button></section></>}
function Card({icon,label,value}:{icon:any;label:string;value:string}){return <article className="metric-card"><div className="metric-icon">{icon}</div><span className="metric-label">{label}</span><strong>{value}</strong></article>}
function List({entity,store,query,setQuery,edit,create,remove}:{entity:Entity;store:Store;query:string;setQuery:(s:string)=>void;edit:(x:Item)=>void;create:()=>void;remove:(e:Entity,id:number)=>void}){const name=(id:number)=>store.Alunos.find(x=>x.id_aluno===id)?.nome??'—',plan=(id:number)=>store.Planos.find(x=>x.id_plano===id)?.nome_plano??'—',trainer=(id:number)=>store.Instrutores.find(x=>x.id_instrutor===id)?.nome??'—';const rows=useMemo(()=>store[entity].filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[store,entity,query]);const cells=(x:Item)=>entity==='Alunos'?[<td><div className="car-cell"><img src={x.foto||avatar}/><div><strong>{x.nome}</strong><span>{x.email}</span></div></div></td>,<td>{plan(x.id_plano)}</td>,<td>{date(x.data_cadastro||x.status)}</td>]:entity==='Planos'?[<td><strong>{x.nome_plano}</strong><br/><small>{x.descricao}</small></td>,<td>{x.duracao_meses} meses</td>,<td>{money(x.valor_plano)}</td>,<td><Badge value={x.ativo}/></td>]:entity==='Instrutores'?[<td><div className="car-cell"><img src={x.foto||avatar}/><div><strong>{x.nome}</strong><span>{x.email}</span></div></div></td>,<td>{x.especialidade}</td>,<td><Badge value={x.ativo}/></td>]:entity==='Treinos'?[<td><strong>{x.objetivo}</strong><br/><small>{x.observacoes}</small></td>,<td>{name(x.id_aluno)}</td>,<td>{trainer(x.id_instrutor)}</td>,<td>{date(x.data_entrada)}</td>]:[<td>{name(x.id_aluno)}</td>,<td>{plan(x.id_plano)}</td>,<td>{money(x.valor)}</td>,<td><Badge value={x.status_pagamento}/></td>,<td>{date(x.data_vencimento)}</td>];return <section><section className="page-heading"><div><p className="eyebrow">CADASTROS</p><h1>{entity}</h1><p className="subheading">Cadastre, edite e acompanhe {entity.toLowerCase()}.</p></div><button className="primary-button" onClick={create}><Plus size={18}/>Novo {singular[entity]}</button></section><div className="toolbar"><div className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar ${singular[entity]}...`}/></div></div><div className="table-wrap"><table><thead><tr>{headers[entity].map(x=><th key={x}>{x}</th>)}<th/></tr></thead><tbody>{rows.map(x=><tr key={x[keys[entity]]}>{cells(x)}<td><div className="row-actions"><button onClick={()=>edit(x)}><Pencil size={15}/></button><button onClick={()=>remove(entity,x[keys[entity]])}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-state">Nenhum registro encontrado.</div>}</div></section>}
const headers:Record<Entity,string[]>={Alunos:['ALUNO','PLANO','CADASTRO'],Planos:['PLANO','DURAÇÃO','VALOR','STATUS'],Instrutores:['INSTRUTOR','ESPECIALIDADE','STATUS'],Treinos:['OBJETIVO','ALUNO','INSTRUTOR','INÍCIO'],Pagamentos:['ALUNO','PLANO','VALOR','STATUS','VENCIMENTO']}
function Badge({value}:{value:any}){const good=value===true||value==='Pago';return <span className={`status ${good?'available':'featured'}`}><i/>{typeof value==='boolean'?(value?'Ativo':'Inativo'):value}</span>}
function Form({entity,value,store,close,save}:{entity:Entity;value?:Item;store:Store;close:()=>void;save:(e:Entity,v:Item)=>void}){const [data,setData]=useState<Item>(value??defaults[entity]);const change=(k:string,v:any)=>setData(d=>({...d,[k]:v}));const selectOptions=(type?:string)=>type==='student'?store.Alunos.map(x=>[x.id_aluno,x.nome]):type==='plan'?store.Planos.map(x=>[x.id_plano,x.nome_plano]):type==='instructor'?store.Instrutores.map(x=>[x.id_instrutor,x.nome]):[];return <div className="modal-backdrop"><form className="form-modal" onSubmit={(e:FormEvent)=>{e.preventDefault();save(entity,data)}}><div className="modal-heading"><div><p className="eyebrow">{value?'EDIÇÃO':'NOVO CADASTRO'}</p><h2>{value?'Editar':'Novo'} {singular[entity]}</h2></div><button type="button" className="icon-button" onClick={close}><X/></button></div><div className="form-grid">{fields[entity].map(f=>{const opts=f.options?.map(x=>[x,x])??(f.type==='boolean'?[['true','Ativo'],['false','Inativo']]:selectOptions(f.type));return <label className={f.type==='textarea'?'wide':''} key={f.key}>{f.label}{f.type==='textarea'?<textarea value={data[f.key]??''} onChange={e=>change(f.key,e.target.value)}/>:opts.length?<select value={String(data[f.key])} onChange={e=>change(f.key,f.type==='boolean'?e.target.value==='true':(['student','plan','instructor'].includes(f.type||'')?Number(e.target.value):e.target.value))}>{opts.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>:<input required type={f.type||'text'} value={data[f.key]??''} onChange={e=>change(f.key,f.type==='number'?Number(e.target.value):e.target.value)}/>}</label>})}</div><div className="form-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button">Salvar {singular[entity]}</button></div></form></div>}
